# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: check-added-large-files
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-symlinks
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: detect-private-key
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: trailing-whitespace

-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
    - id: shellcheck
      args: [-x]
    - id: shfmt
      args: [-i 2]

-   repo: git://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
    - id: shell-lint
      args: [-x]
