#!/bin/bash

export GO_VERSION='1.14.7'
export CFSSL_GIT_VERSION='v1.4.1'
export CNI_GIT_VERSION='v0.8.6'
export CONTAINERD_GIT_VERSION='v1.3.6'
export ETCD_GIT_VERSION='v3.4.10'
export KUBERNETES_GIT_VERSION='v1.16.13'
export SONOBUOY_VERSION='0.16.5'
export SONOBUOY_VERSION='0.17.2'
export SONOBUOY_VERSION='0.18.5'
export CRICTL_VERSION='v1.16.1'
export RUNC_GIT_VERSION='v1.0.0-rc91'
export HELM_VERSION='3.3.4'

export K8SFS_CACHE_LOCATION=${K8SFS_CACHE_LOCATION:-~/.k8sfs}
export K8SFS_TARGET_LOCATION=${K8SFS_TARGET_LOCATION:-/opt/k8sfs}
export K8SFS_CERT_LOCATION="${K8SFS_TARGET_LOCATION}/kubernetes/pki"
export K8SFS_KUBECONFIG_LOCATION="${K8SFS_TARGET_LOCATION}/kubernetes/etc"
export K8SFS_MANIFESTS_LOCATION="${K8SFS_TARGET_LOCATION}/kubernetes/manifests"
export K8SFS_RUNTIME_DIR="${K8SFS_TARGET_LOCATION}/run"

export GOPATH=${GOPATH:-~/go}
export PATH=${K8SFS_TARGET_LOCATION}/kubernetes/${KUBERNETES_GIT_VERSION}/bin:${K8SFS_TARGET_LOCATION}/go/${GO_VERSION}/go/bin:${K8SFS_TARGET_LOCATION}/etcd/${ETCD_GIT_VERSION}/bin:${K8SFS_TARGET_LOCATION}/sonobuoy/${SONOBUOY_VERSION}/bin:${K8SFS_TARGET_LOCATION}/containerd/${CONTAINERD_GIT_VERSION}/bin:${K8SFS_TARGET_LOCATION}/etcd/${ETCD_GIT_VERSION}/bin:${K8SFS_TARGET_LOCATION}/crictl/${CRICTL_VERSION}/bin:${K8SFS_TARGET_LOCATION}/helm/${HELM_VERSION}/bin:$PATH

export KUBECONFIG=${K8SFS_KUBECONFIG_LOCATION}/admin.kubeconfig
