kind: KubeProxyConfiguration
apiVersion: kubeproxy.config.k8s.io/v1alpha1
clientConnection:
  kubeconfig: "${K8SFS_KUBECONFIG_LOCATION}/kube-proxy.kubeconfig"
mode: "iptables"
clusterCIDR: "10.244.0.0/24"
